# Generated by Django 4.1.10 on 2023-07-10 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appgame', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='profilimg',
            field=models.ImageField(default='person.png', upload_to='ProfilFotoğrafları', verbose_name='Profil Fotoğrafı'),
        ),
    ]
